# This needs at least compose 1.6.0
version: '2'

services:
  huginn:
    image: huginn/huginn
    restart: always
    volumes:
      - huginn-docker-specs-mysql:/var/lib/mysql
    ports:
      - 3000:3000
volumes:
  huginn-docker-specs-mysql:
    external: true
