# This needs at least compose 1.6.0
version: '2'

services:
  mysqldata:
    image: mysql:5.7
    command: /bin/true

  mysql:
    image: mysql:5.7
    volumes_from:
      - mysqldata
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: huginn_production
      MYSQL_USER: huginn
      MYSQL_PASSWORD: myhuginnpassword

  huginn:
    image: huginn/huginn
    restart: always
    environment:
      HUGINN_DATABASE_NAME: huginn_production
      HUGINN_DATABASE_USERNAME: huginn
      HUGINN_DATABASE_PASSWORD: myhuginnpassword
      INTENTIONALLY_SLEEP: 10
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      DO_NOT_SEED: 'true'
      DO_NOT_CREATE_DATABASE: 'true'
      ADDITIONAL_GEMS: "huginn_website_metadata_agent(github: kreuzwerker/DKT.huginn_website_metadata_agent),huginn_readability_agent(github: kreuzwerker/DKT.huginn_readability_agent)"
      APP_SECRET_TOKEN: secret
    ports:
      - 3000:3000
    links:
      - mysql
