# This needs at least compose 1.6.0
version: '2'

services:
  postgresdata:
    image: postgres:9.5
    command: /bin/true

  postgres:
    image: postgres:9.5
    volumes_from:
      - postgresdata
    environment:
      POSTGRES_PASSWORD: myhuginnpassword
      POSTGRES_USER: huginn

  huginn:
    image: huginn/huginn-single-process
    restart: always
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: myhuginnpassword
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - postgres

  huginn_threaded:
    image: huginn/huginn-single-process
    restart: always
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: myhuginnpassword
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
    env_file:
      - .env
    links:
      - postgres
    command: /scripts/init bin/threaded.rb
